name: Go

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch: # Enables the web UI manual trigger

permissions:
  pull-requests: write

jobs:
  test:
    name: Test
    runs-on: ubuntu-22.04
    timeout-minutes: 15
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4.0.0
        with:
          submodules: recursive

      - name: Set up Go
        uses: actions/setup-go@v4.1.0
        with:
          go-version: ^1

      - name: Vet Go code
        run: go vet ./...

      - name: Run Go tests
        run: go test -mod=readonly -v -race ./...

      - name: Verify repo is unchanged
        run: git diff --exit-code HEAD

  approve:
    runs-on: ubuntu-22.04
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1.6.0
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Approve PR
        run: gh pr review --approve "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
